import { IFile } from '../i-file';

export const unityExampleProjectFiles: IFile[] = [
  {
    file: 'README.md',
    contents: '# My Project',
  },
  {
    file: '.gitignore',
    contents: `
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/Assets/AssetStoreTools*

# Visual Studio 2015 cache directory
/.vs/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb

# Unity3D generated meta files
*.pidb.meta

# Unity3D Generated File On Crash Reports
sysinfo.txt

# Builds
*.apk
        `,
  },
  {
    file: 'maniferst.json',
    path: 'UnityPackageManager',
    contents: `
{
	"dependencies": {
	}
}
        `,
  },
  {
    file: 'ProjectVersion.txt',
    path: 'ProjectSettings',
    contents: 'm_EditorVersion: 2017.3.0p1',
  },
  {
    file: 'MyCustomScript.cs',
    path: 'Assets/MyProject/Scripts',
  },
  {
    file: 'MyExample.scene',
    path: 'Assets/MyProject/Examples',
  },
  {
    file: 'Examples.meta',
    path: 'Assets/MyProject',
  },
  {
    file: 'MyTest.cs',
    path: 'Assets/MyProject/Testing',
  },
  {
    file: 'Testing.meta',
    path: 'Assets/MyProject',
  },
  {
    file: 'Ignore.cs',
    path: 'Assets/MyProject/Ignore',
  },
  {
    file: 'Ignore.meta',
    path: 'Assets/MyProject',
  },
  {
    file: 'MyPlugin.cs',
    path: 'Assets/Plugins/MyPlugin',
  },
  {
    file: 'Dist.unitypackage',
    path: 'Assets/Dist',
  },
  {
    file: 'placeholder.txt',
    path: '.git',
  },
];
